CREATE TABLE STATUS(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	STATUS VARCHAR(25) NOT NULL
);

INSERT INTO 
	STATUS (STATUS) 
VALUES 
	('PENDENTE'), 
	('REALIZADO');
	
CREATE TABLE LISTA_TAREFAS.TAREFAS (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_STATUS INT NOT NULL DEFAULT 1,
	FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID),
	DSC_TAREFA TEXT NOT NULL,
	DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP